version: '3.7'

services:
        web:
                build: .
                command: /code/wait-for-it.sh db:5432 -t 30 --strict -- python /code/manage.py runserver 0.0.0.0:8000
                volumes:
                        - .:/code
                ports:
                        - 8000:8000
                depends_on:
                        - db
        db:
                image: postgres:11
                environment:
                        - POSTGRES_DB=bookstore
                        - POSTGRES_USER=postgres
                        - POSTGRES_PASSWORD=9508
                volumes:
                        - postgres_data:/var/lib/postgres/data

volumes:
        postgres_data: {}
